[package]
name = "sfs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_urlencoded = "0.7.1"
tiny_http = "0.12.0"
url = "2.5.2"
webbrowser = "1.0.1"
